### ISSUE TITLE
Login Form JS not working

### ISSUE THREAD

**Issue by marksie1988** [CawaKharkov/admin-view#1]
Hey like what you have done here. 

Please could you help me, I have done the login form the same as for this template but it doesnt do the shake when the username and password are blank, it just highlights them red. 

Im not sure how to get this working there are no errors for the js in firefox debugger or the nginx logs

**Comment by cawa87** [comment]
Hey, can I see the code?

**Comment by marksie1988** [comment]
Hey sorry forgot this was still here. I managed to get it working. It was because I placed the JS at the top rather than bottom.
